- name: Set up Arch Linux environment for Marius
  hosts: localhost
  become: yes
  vars:
    user_name: "marius"
    group_name: "wheel"
    workspace_dir: "/home/{{ user_name }}/workspace"
    packages:
      - btop
      - clang
      - conky
      - bash-completion
      - curl
      - dmenu
      - docker
      - docker-compose
      - eza
      - fastfetch
      - fd
      - git
      - go
      - i3
      - kitty
      - tig
      - fzf
      - kubectl
      - lua51
      - neovim
      - ripgrep
      - rofi
      - rustup
      - unzip
      - tmux
      - yazi
  tasks:
    - name: Ensure the workspace directory exists
      file:
        path: "{{ workspace_dir }}"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        mode: '0755'
    - name: Update the package database
      pacman:
        update_cache: yes
    - name: Install required packages
      pacman:
        name: "{{ packages }}"
        state: present
    - name: Ensure destination directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        mode: '0755'
      with_items:
        - "/home/{{ user_name }}/.config/kitty"
        - "/home/{{ user_name }}/.config/rofi"
        - "/usr/local/bin"
    - name: Clone the dots repository
      git:
        repo: https://github.com/mariusmagureanu/dots
        dest: "{{ workspace_dir }}/dots"
        update: yes
        version: alt
    - name: Clone the yay repository
      git:
        repo: https://github.com/Jguer/yay.git
        dest: "{{ workspace_dir }}/yay"
        update: yes
        version: master
    - name: Install yay
      command: "makepkg -Sif"
      become: yes
      become_user: "{{ user_name }}"
      args:
        chdir: "{{ workspace_dir }}/yay"
    - name: Create or update the ~/.config/nvim symlink
      file:
        src: "{{ workspace_dir }}/dots/nvim-lua"
        dest: "/home/{{ user_name }}/.config/nvim"
        state: link
    - name: Install Adobe Source Code Pro font
      pacman:
        name: ttf-sourcecodepro-nerd
        state: present
    - name: Copy configuration and script files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        mode: "{{ item.mode }}"
      with_items:
        - {src: "{{ workspace_dir }}/dots/kitty.conf", dest: "/home/{{ user_name }}/.config/kitty/kitty.conf", mode: '0644'}
        - {src: "{{ workspace_dir }}/dots/rofi.config", dest: "/home/{{ user_name }}/.config/rofi/config", mode: '0644'}
        - {src: "{{ workspace_dir }}/dots/rofi-computer", dest: "/usr/local/bin/rofi-computer", mode: '0755'}
        - {src: "{{ workspace_dir }}/dots/conky-i3bar.sh", dest: "/usr/local/bin/conky-i3bar.sh", mode: '0755'}
        - {src: "{{ workspace_dir }}/dots/i3-keyboard-layout", dest: "/usr/local/bin/i3-keyboard-layout", mode: '0755'}
        - {src: "{{ workspace_dir }}/dots/.conkyrc", dest: "/home/{{ user_name }}/.conkyrc", mode: '0644'}
        - {src: "{{ workspace_dir }}/dots/.LESS_TERMCAP", dest: "/home/{{ user_name }}/.LESS_TERMCAP", mode: '0644'}
    - name: Install various YAY packages
      command: yay -S --noconfirm tfenv
      become: yes
      become_user: "{{ user_name }}"
