shell_integration enabled
scrollback_lines 20000
enable_audio_bell no
repaint_delay 6
input_delay 1
sync_to_monitor no
font_size 10

font_family JetBrains Mono Nerd Font
#font_family Source Code Pro


# BEGIN_KITTY_THEME
# Argonaut
include current-theme.conf
# END_KITTY_THEME
