name: Install Dots
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-dots:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - name: Install dependencies
        run: pacman -Sy --noconfirm ansible sudo git base-devel fakeroot debugedit go
      - uses: actions/checkout@v4
      - name: Create user
        run: useradd -m -G wheel marius
      - name: Run Ansible Playbook
        run: ansible-playbook hecker.yml
